name: Main

permissions:
  contents: write

on: [push]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            toolchain: nightly
            use-cross: false
          - os: macos-14 # M1
            target: aarch64-apple-darwin
            use-cross: false
            toolchain: nightly

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest nightly for ${{ matrix.os }}
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.toolchain }}
            target: ${{ matrix.target }}
            override: false

      - name: Build 
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
          use-cross: ${{ matrix.use_cross }}

      - name: Run build
        run: cargo build
